D:\Faculty materials\BACHELORS-THESIS\.venv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(
Epoch 1/10
D:\Faculty materials\BACHELORS-THESIS\.venv\lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:120: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()
































































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m147s[22m 282ms/step - accuracy: 0.3403 - loss: 2.4244 - val_accuracy: 0.2682 - val_loss: 3.4119
Epoch 2/10






































































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m147s[22m 297ms/step - accuracy: 0.8665 - loss: 0.4167 - val_accuracy: 0.9392 - val_loss: 0.1889
Epoch 3/10






































































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m148s[22m 298ms/step - accuracy: 0.9445 - loss: 0.1797 - val_accuracy: 0.9467 - val_loss: 0.1739
Epoch 4/10




































































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m142s[22m 287ms/step - accuracy: 0.9594 - loss: 0.1259 - val_accuracy: 0.9825 - val_loss: 0.0602
Epoch 5/10






























































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m132s[22m 266ms/step - accuracy: 0.9711 - loss: 0.0921 - val_accuracy: 0.9691 - val_loss: 0.1025
Epoch 6/10






























































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m133s[22m 268ms/step - accuracy: 0.9751 - loss: 0.0833 - val_accuracy: 0.9881 - val_loss: 0.0360
Epoch 7/10































































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m135s[22m 273ms/step - accuracy: 0.9776 - loss: 0.0708 - val_accuracy: 0.9897 - val_loss: 0.0336
Epoch 8/10















































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m101s[22m 203ms/step - accuracy: 0.9806 - loss: 0.0640 - val_accuracy: 0.9308 - val_loss: 0.2472
Epoch 9/10











































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m91s[22m 184ms/step - accuracy: 0.9822 - loss: 0.0572 - val_accuracy: 0.9917 - val_loss: 0.0246
Epoch 10/10












































[1m491/491[22m [32m━━━━━━━━━━━━━━━━━━━━[39m [1m91s[22m 184ms/step - accuracy: 0.9839 - loss: 0.0530 - val_accuracy: 0.9923 - val_loss: 0.0260
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.